Backport: Add support for `Dimension(...).grain(...)` in where filter
dbt-labs/dbt-semantic-interfaces pull request #162
Opened 2023-09-29 17:44 UTC by DevonFulcher

Resolving: SL-631

### Description

Due to MetricFlow's reliance on version 0.2.x of DSI, the updates to support `Dimension(...).grain(...)` need to be made to this branch as well. I just combined the work from these PRs into this one https://github.com/dbt-labs/dbt-semantic-interfaces/pull/156, https://github.com/dbt-labs/dbt-semantic-interfaces/pull/154, https://github.com/dbt-labs/dbt-semantic-interfaces/pull/152

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2023-09-30 01:01 UTC, tlento reviewed
This all seems fine to me, given my understanding of the changes and how the backport deployment works with core 1.6.x,  but I'd like @QMalcolm to take a look to confirm this is backwards compatible with existing 1.6 installations. In particular, I think there are some changes to the where_filter_parser along with the file move here.

2023-10-02 20:37 UTC, QMalcolm reviewed
I unfortunately don't think we can back port this. Core imports the WhereFilterParser, and this changes that import path. Core's import of DSI is `~=0.2.0` in dbt-core `1.6.0` through `1.6.5`, if we backported and released this, all fresh installs of those versions would break.

2023-10-02 21:12 UTC, tlento commented
> I unfortunately don't think we can back port this. Core imports the WhereFilterParser, and this changes that import path. Core's import of DSI is ~=0.2.0 in dbt-core 1.6.0 through 1.6.5, if we backported and released this, all fresh installs of those versions would break.

Is that the only issue? If so, can we add an import alias to the backport then? We should be able to put in a module in the original location that imports this WhereFilterParser (or defines a WhereFilterParser class that wraps it, if there are API changes that need to be managed).

2023-10-02 21:20 UTC, QMalcolm requested changes
@DevonFulcher brought up the idea of moving the `where_filter_parser.py` file back out for the backport in slack, also @tlento brought it in an above comment. Combing through these changes, and imports of `dbt-semantic-interfaces` in `dbt-core`, I think we can get away with this by doing so.

2023-10-02 22:35 UTC, QMalcolm approved these changes

2023-10-02 22:52 UTC, tlento commented
Yay! 🚢

2023-10-03 15:09 UTC, merged