Expose meta in DSI
dbt-labs/dbt-semantic-interfaces pull request #250
Opened 2024-01-20 00:32 UTC by WilliamDee

Resolves #

### Description

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

2024-01-20 00:37 UTC, courtneyholcomb approved these changes

2024-02-09 19:13 UTC, QMalcolm requested changes
Howdy! Thank you for doing this work @WilliamDee. There are some small changes we need to make before proceeding.

2024-02-09 19:13 UTC, QMalcolm commented on dbt_semantic_interfaces/implementations/metric.py
> +    meta: Dict[str, Any] = {}
We should move this under a `config` property as we have done in `SemanticModel`. We should do this for two reasons
1. Consistency across the protocols (meta should always be found in the same place)
2. In dbt-core the direct `meta` attribute is deprecated in favor of `meta` being under the `config` property
  a. In accordance with this, we have an [open issue](https://github.com/dbt-labs/dbt-core/issues/9441) which we plan to take on shortly to bring the core definition of `Metric` into alignment 
  
Additionally we should update the default setting to
```
meta: Dict[str, Any] = Field(default_factory=dict)
```
as described in another comment

2024-02-09 19:13 UTC, QMalcolm commented on dbt_semantic_interfaces/protocols/metric.py
> +
We should move this to be nested under a `config` property similar to what we're doing in the `SemanticModel`

2024-02-09 19:13 UTC, QMalcolm commented on dbt_semantic_interfaces/parsing/schemas.py
> +        "meta": {"type": "object", "propertyNames": {"type": "string"}},
This will also need to get updated to have it nested under `config`

2024-02-09 19:13 UTC, QMalcolm commented on dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
> +                },
This should get changed when regenerating the file after updated `schemas.py`

2024-02-27 19:08 UTC, WilliamDee commented on dbt_semantic_interfaces/implementations/semantic_model.py
> +    meta: Dict[str, Any] = {}
ooohh TIL!

2024-02-27 19:18 UTC, WilliamDee commented
@QMalcolm this piece should be ready to go! I believe core needs to update that nested config for Metric and we should be able to merge this

2024-02-27 19:30 UTC, QMalcolm approved these changes
Looks good, one small nit on consistency

2024-02-27 19:30 UTC, QMalcolm commented on dbt_semantic_interfaces/protocols/__init__.py
> +    SemanticModelConfig,
Is there a reason we also didn't add `MetricConfig` to the imports from `metric` on line 13?

2024-02-27 19:30 UTC, QMalcolm commented on dbt_semantic_interfaces/implementations/metric.py
> +from dbt_semantic_interfaces.protocols.metric import MetricConfig
Nit: We should add `MetricConfig` to the protocols `__init__.py` so that we can import it from the `protocols` path.

2024-03-11 17:43 UTC, merged